<footer>
        <div class="footer-container">
            <div class="footer-links">
                <ul>
                    <li><a href="privacy.html">Privacy Policy</a></li>
                    <li><a href="terms.html">Terms of Service</a></li>
                    <li><a href="mailto:info@bluewaveit.com.au">Contact Us</a></li>
                </ul>
            </div>
            <div class="footer-info">
                <p>© 2025 Bluewave IT.</p>
                <p><a href="https://igglepigglesite.atlassian.net/jira/software/projects/P1/boards/34">View Jira Project</a></p>
            </div>
        </div>
    </footer>
</body>
</html>
