<nav class="main-nav">
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="about.php">About Us</a></li>
        <li><a href="jobs.php">Job Descriptions</a></li>
        <li><a href="job_database.php">Jobs Database</a></li>
        <li><a href="apply.php">Apply for Job</a></li>
        <li><a href="manage.php">HR Management</a></li>
    </ul>
</nav>
</div>
</header>
